### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by 3020** [Flyguygx/sd-webui-panorama-tools#1]
In newer versions of Automatic1111 it wont work?

*** Error executing callback ui_tabs_callback for ...\stable-diffusion-webui\extensions\sd-webui-panorama-tools\scripts\panorama-tools.py
    Traceback (most recent call last):
      File "...\stable-diffusion-webui\modules\script_callbacks.py", line 180, in ui_tabs_callback
        res += c.callback() or []
      File ",,,\stable-diffusion-webui\extensions\sd-webui-panorama-tools\scripts\panorama-tools.py", line 268, in on_ui_tabs
        sendSketchToTxt2ImgControlNet.click(fn=None,inputs=[],outputs=[sendto_controlnet_inputs["txt2img"][0]], show_progress=False,
    IndexError: list index out of range

---

**Comment by 3020** [comment]
Nevermind (for future stumpers -if any-):

Solved once ControlNet extension was correctly installed.

I would suggest not to mark it as *recommended* but stated as ***pre-requisite*** instead  (https://github.com/Flyguygx/sd-webui-panorama-tools#recommended-extensions)

**Comment by Flyguygx** [comment]
This is a bug actually, it's supposed to just grey-out those buttons if ControlNet isn't detected but it looks like that check is missing in the initialization code which causes that error. 
Fixed in commit d60055b
