### ISSUE TITLE
Where is the "From Output" button?

### ISSUE THREAD

**Issue by IamTirion** [Flyguygx/sd-webui-panorama-tools#2]
In your Outpainting workflow, step 5, it says 

> Click "From Output" under the panorama input to apply the inpainting image.

I still cannot find this button despite the instructions. Can you show me where it is please? Thank you.

**Comment by Flyguygx** [comment]
"From Output" is actually the old name for the "Apply Changes" button.
I renamed it some time after writing the workflows but forgot to go back and correct them.
The workflows are updated now.
